theme[main_bg]="#171614"
theme[main_fg]="#f0eeeb"
theme[title]="#f0eeeb"
theme[hi_fg]="#d9d7d4"
theme[selected_bg]="#acaaa8"
theme[selected_fg]="#171614"
theme[inactive_fg]="#81807d"
theme[proc_misc]="#f0eeeb"
theme[div_line]="#646361"
theme[meter_bg]="#171614"
theme[graph_text]="#81807d"

theme[process_start]="#f0eeeb"
theme[process_mid]="#f0eeeb"
theme[process_end]="#f0eeeb"

theme[cpu_box]="#646361"
theme[mem_box]="#646361"
theme[net_box]="#646361"
theme[proc_box]="#646361"

theme[temp_start]="#acaaa8"
theme[temp_mid]="#c2c1be"
theme[temp_end]="#d9d7d4"

theme[cpu_start]="#acaaa8"
theme[cpu_mid]="#c2c1be"
theme[cpu_end]="#d9d7d4"

theme[free_start]="#acaaa8"
theme[free_mid]="#c2c1be"
theme[free_end]="#d9d7d4"

# Also used for the GPU power readout.
theme[cached_start]="#acaaa8"
theme[cached_mid]="#c2c1be"
theme[cached_end]="#d9d7d4"

theme[available_start]="#acaaa8"
theme[available_mid]="#c2c1be"
theme[available_end]="#d9d7d4"

theme[used_start]="#acaaa8"
theme[used_mid]="#c2c1be"
theme[used_end]="#d9d7d4"

theme[download_start]="#acaaa8"
theme[download_mid]="#c2c1be"
theme[download_end]="#d9d7d4"

theme[upload_start]="#acaaa8"
theme[upload_mid]="#c2c1be"
theme[upload_end]="#d9d7d4"
