theme[main_bg]="#090909"
theme[main_fg]="#f1e6dc"
theme[title]="#f1e6dc"
theme[hi_fg]="#d8cec4"
theme[selected_bg]="#f1e6dc"
theme[selected_fg]="#090909"
theme[inactive_fg]="#898078"
theme[proc_misc]="#f1e6dc"
theme[div_line]="#aaa19a"
theme[meter_bg]="#090909"
theme[graph_text]="#898078"

theme[process_start]="#f1e6dc"
theme[process_mid]="#f1e6dc"
theme[process_end]="#f1e6dc"

theme[cpu_box]="#aaa19a"
theme[mem_box]="#aaa19a"
theme[net_box]="#aaa19a"
theme[proc_box]="#aaa19a"

theme[temp_start]="#f1e6dc"
theme[temp_mid]="#aaa19a"
theme[temp_end]="#aaa19a"

theme[cpu_start]="#aaa19a"
theme[cpu_mid]="#b6ada5"
theme[cpu_end]="#d8cec4"

theme[free_start]="#aaa19a"
theme[free_mid]="#b6ada5"
theme[free_end]="#d8cec4"

# Also used for the GPU power readout.
theme[cached_start]="#aaa19a"
theme[cached_mid]="#b6ada5"
theme[cached_end]="#d8cec4"

theme[available_start]="#aaa19a"
theme[available_mid]="#b6ada5"
theme[available_end]="#d8cec4"

theme[used_start]="#aaa19a"
theme[used_mid]="#b6ada5"
theme[used_end]="#d8cec4"

theme[download_start]="#aaa19a"
theme[download_mid]="#b6ada5"
theme[download_end]="#d8cec4"

theme[upload_start]="#aaa19a"
theme[upload_mid]="#b6ada5"
theme[upload_end]="#d8cec4"
