theme[main_bg]="#090909"
theme[main_fg]="#f3f3f3"
theme[title]="#fcf2e9"
theme[hi_fg]="#e0d7ce"
theme[selected_bg]="#f3f3f3"
theme[selected_fg]="#090909"
theme[inactive_fg]="#877e76"
theme[proc_misc]="#f3f3f3"
theme[div_line]="#978e86"
theme[meter_bg]="#090909"
theme[graph_text]="#877e76"

theme[process_start]="#f3f3f3"
theme[process_mid]="#fcf2e9"
theme[process_end]="#fcf2e9"

theme[cpu_box]="#978e86"
theme[mem_box]="#978e86"
theme[net_box]="#978e86"
theme[proc_box]="#978e86"

theme[temp_start]="#f3f3f3"
theme[temp_mid]="#aaa198"
theme[temp_end]="#aaa198"

theme[cpu_start]="#978e86"
theme[cpu_mid]="#9e958d"
theme[cpu_end]="#e0d7ce"

theme[free_start]="#978e86"
theme[free_mid]="#9e958d"
theme[free_end]="#e0d7ce"

# Also used for the GPU power readout.
theme[cached_start]="#978e86"
theme[cached_mid]="#9e958d"
theme[cached_end]="#e0d7ce"

theme[available_start]="#978e86"
theme[available_mid]="#9e958d"
theme[available_end]="#e0d7ce"

theme[used_start]="#978e86"
theme[used_mid]="#9e958d"
theme[used_end]="#e0d7ce"

theme[download_start]="#978e86"
theme[download_mid]="#9e958d"
theme[download_end]="#e0d7ce"

theme[upload_start]="#978e86"
theme[upload_mid]="#9e958d"
theme[upload_end]="#e0d7ce"
