hover_effect_color=#978e86
held_element_color=#aaa198
middle_buttons_color=#f3f3f3
osc_color=#090909
playpause_color=#f3f3f3
seek_handle_color=#978e86
seek_handle_border_color=#090909
seekbarfg_color=#978e86
seekbarbg_color=#1b1917
seekbar_cache_color=#e0d7ce
side_buttons_color=#f3f3f3
time_color=#f3f3f3
title_color=#f3f3f3
window_title_color=#f3f3f3
window_controls_color=#f3f3f3
windowcontrols_close_hover=#aaa198
windowcontrols_max_hover=#978e86
windowcontrols_min_hover=#978e86
chapter_title_color=#f3f3f3
cache_info_color=#8e857d
thumbnail_box_color=#1b1917
thumbnail_box_outline=#7b726b
nibble_color=#978e86
nibble_current_color=#fcf2e9
ab_loop_color=#9e958d
