hover_effect_color=#aaa19a
held_element_color=#aaa19a
middle_buttons_color=#f1e6dc
osc_color=#090909
playpause_color=#f1e6dc
seek_handle_color=#aaa19a
seek_handle_border_color=#090909
seekbarfg_color=#aaa19a
seekbarbg_color=#1b1917
seekbar_cache_color=#d8cec4
side_buttons_color=#f1e6dc
time_color=#f1e6dc
title_color=#f1e6dc
window_title_color=#f1e6dc
window_controls_color=#f1e6dc
windowcontrols_close_hover=#aaa19a
windowcontrols_max_hover=#aaa19a
windowcontrols_min_hover=#aaa19a
chapter_title_color=#f1e6dc
cache_info_color=#898078
thumbnail_box_color=#1b1917
thumbnail_box_outline=#898078
nibble_color=#aaa19a
nibble_current_color=#f1e6dc
ab_loop_color=#b6ada5
