hover_effect_color=#c2c1be
held_element_color=#acaaa8
middle_buttons_color=#f0eeeb
osc_color=#171614
playpause_color=#f0eeeb
seek_handle_color=#acaaa8
seek_handle_border_color=#171614
seekbarfg_color=#646361
seekbarbg_color=#171614
seekbar_cache_color=#81807d
side_buttons_color=#f0eeeb
time_color=#acaaa8
title_color=#f0eeeb
window_title_color=#f0eeeb
window_controls_color=#f0eeeb
windowcontrols_close_hover=#d9d7d4
windowcontrols_max_hover=#c2c1be
windowcontrols_min_hover=#c2c1be
chapter_title_color=#f0eeeb
cache_info_color=#81807d
thumbnail_box_color=#171614
thumbnail_box_outline=#646361
nibble_color=#acaaa8
nibble_current_color=#f0eeeb
ab_loop_color=#acaaa8
