#!/usr/bin/env bash

set -Eeuo pipefail

if [[ $# -ne 1 || ${1:-} != title ]]; then
  printf 'usage: bar-mango title\n' >&2
  exit 2
fi

mmsg watch all-monitors | jq --unbuffered -c '
  ([.monitors[]? | select(.active)][0] // {}) as $monitor |
  {text: ($monitor.active_client.title // "")}'
